# Generated by Django 4.0.3 on 2022-04-06 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lesson_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tittle',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
